import { useState, useRef, useEffect, useCallback, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { useIsMobile } from "@/hooks/use-mobile";
import { useUserPreferences } from "@/hooks/useUserPreferences";
import { useAuth } from "@/contexts/AuthContext";
import TidingsHeader from "@/components/TidingsHeader";
import TidingCard from "@/components/TidingCard";
import FullscreenTidingCard from "@/components/FullscreenTidingCard";
import CategoryFilter from "@/components/CategoryFilter";
import { TIDINGS_DATA, type TidingDetail } from "@/data/tidings";
import { supabase } from "@/integrations/supabase/client";
import { Sparkles, Loader2, ArrowLeft, User } from "lucide-react";
import { toast } from "sonner";
import type { TidingData } from "@/components/TidingCard";
import tidingDefault from "@/assets/tiding-default.jpg";

type AiTiding = TidingData & { voiceover?: string; headline?: string; imagePrompt?: string };

const Index = () => {
  const [filter, setFilter] = useState("all");
  const [aiTidings, setAiTidings] = useState<AiTiding[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [personalizedMode, setPersonalizedMode] = useState(false);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();
  const isMobile = useIsMobile();
  const { user } = useAuth();
  const { preferences } = useUserPreferences();

  const allTidings: (TidingDetail | AiTiding)[] = [
    ...aiTidings,
    ...TIDINGS_DATA,
  ];

  // Apply personalized filtering based on user preferences
  const filtered = useMemo(() => {
    let result = allTidings;

    // Apply category filter from UI
    if (filter !== "all") {
      result = result.filter((t) => t.category === filter);
    }

    // Apply personalized preferences when enabled
    if (personalizedMode && preferences) {
      const { preferred_categories, preferred_traditions } = preferences;
      const hasCategories = preferred_categories.length > 0 && !preferred_categories.includes("all");
      const hasTraditions = preferred_traditions.length > 0 && !preferred_traditions.includes("all");

      if (hasCategories || hasTraditions) {
        result = result.filter((t) => {
          const categoryMatch = !hasCategories || preferred_categories.includes(t.category);
          const traditionMatch = !hasTraditions || t.sources.some((s) => 
            preferred_traditions.some((pref) => 
              s.tradition.toLowerCase().includes(pref.toLowerCase())
            )
          );
          return categoryMatch || traditionMatch;
        });
      }
    }

    return result;
  }, [allTidings, filter, personalizedMode, preferences]);

  const generateTiding = async () => {
    setIsGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-tiding", {
        body: {},
      });
      if (error) throw error;
      if (data?.tiding) {
        const tiding: AiTiding & { videoUrl?: string } = {
          ...data.tiding,
          image: data.tiding.image || tidingDefault,
          videoUrl: data.tiding.videoUrl, // Generated video
        };
        setAiTidings((prev) => [tiding, ...prev]);
        toast.success("New tiding generated by the Oracle");
        // Scroll to top
        setCurrentIndex(0);
        scrollToIndex(0);
      }
    } catch (err: any) {
      console.error("Generation error:", err);
      toast.error(err.message || "Failed to generate tiding");
    } finally {
      setIsGenerating(false);
    }
  };

  // Handle scroll snap for fullscreen mode
  const handleScroll = useCallback(() => {
    if (!scrollContainerRef.current) return;
    const container = scrollContainerRef.current;
    const scrollTop = container.scrollTop;
    const cardHeight = container.clientHeight;
    const newIndex = Math.round(scrollTop / cardHeight);
    if (newIndex !== currentIndex && newIndex >= 0 && newIndex < filtered.length) {
      setCurrentIndex(newIndex);
    }
  }, [currentIndex, filtered.length]);

  const scrollToIndex = (index: number) => {
    if (!scrollContainerRef.current) return;
    const cardHeight = scrollContainerRef.current.clientHeight;
    scrollContainerRef.current.scrollTo({ top: index * cardHeight, behavior: "smooth" });
  };

  useEffect(() => {
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = "";
    };
  }, []);

  // Mobile fullscreen TikTok-style view ONLY
  return (
    <div className="fixed inset-0 bg-background z-50">
      {/* Header overlay */}
      <div className="absolute top-0 left-0 right-0 z-30 flex items-center justify-between p-4 bg-gradient-to-b from-background/80 to-transparent">
        <div className="w-9" /> {/* Spacer to align title */}
        <h1 className="font-display text-lg font-bold text-gradient-gold">TIDINGS</h1>
        <button
          onClick={generateTiding}
          disabled={isGenerating}
          className="p-2 rounded-full bg-oracle/80 backdrop-blur-sm text-oracle-foreground"
        >
          {isGenerating ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
        </button>
      </div>

      {/* Filter pills */}
      <div className="absolute top-16 left-0 right-0 z-30 px-4">
        <CategoryFilter onFilterChange={setFilter} />
      </div>

      {/* Snap scroll container */}
      <div
        ref={scrollContainerRef}
        onScroll={handleScroll}
        className="h-full w-full overflow-y-scroll snap-y snap-mandatory"
        style={{ scrollSnapType: "y mandatory" }}
      >
        {filtered.map((tiding, i) => (
          <div key={tiding.id} className="h-full w-full snap-start snap-always">
            <FullscreenTidingCard
              tiding={tiding as AiTiding}
              index={i}
              total={filtered.length}
              onNavigateUp={() => scrollToIndex(i - 1)}
              onNavigateDown={() => scrollToIndex(i + 1)}
            />
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="h-full w-full flex items-center justify-center">
            <p className="text-muted-foreground font-body">No tidings found.</p>
          </div>
        )}
      </div>

      {/* Page indicator */}
      <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-30">
        <div className="bg-secondary/60 backdrop-blur-sm px-3 py-1 rounded-full text-xs text-secondary-foreground font-body">
          {currentIndex + 1} / {filtered.length}
        </div>
      </div>
    </div>
  );
};

export default Index;
