import { useState, useRef, useEffect, useCallback, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { useUserPreferences } from "@/hooks/useUserPreferences";
import { useAuth } from "@/contexts/AuthContext";
import { useStreaks } from "@/hooks/useStreaks";
import UserMenu from "@/components/UserMenu";
import FullscreenTidingCard from "@/components/FullscreenTidingCard";
import { TIDINGS_DATA, type TidingDetail } from "@/data/tidings";
import { supabase } from "@/integrations/supabase/client";
import { Sparkles, Loader2, Flame, Zap, AlertTriangle, Globe, BookOpen, Swords } from "lucide-react";
import { toast } from "sonner";
import type { TidingData } from "@/components/TidingCard";
import tidingDefault from "@/assets/tiding-default.jpg";

type AiTiding = TidingData & { voiceover?: string; headline?: string; newsSource?: string; newsUrl?: string; imagePrompt?: string; rarity?: string };

type FeedTab = "foryou" | "breaking" | "omens";

const TABS: { id: FeedTab; label: string; icon: typeof Sparkles }[] = [
  { id: "foryou", label: "For You", icon: Sparkles },
  { id: "breaking", label: "Breaking", icon: Zap },
  { id: "omens", label: "Omens", icon: AlertTriangle },
];

const Index = () => {
  const [activeTab, setActiveTab] = useState<FeedTab>("foryou");
  const [aiTidings, setAiTidings] = useState<AiTiding[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [showSwipeHint, setShowSwipeHint] = useState(true);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();
  const { user } = useAuth();
  const { preferences } = useUserPreferences();
  const { streak, recordView, recordReaction, recordGenerate } = useStreaks();

  const allTidings: (TidingDetail | AiTiding)[] = [
    ...aiTidings,
    ...TIDINGS_DATA,
  ];

  // Tab-based filtering
  const filtered = useMemo(() => {
    let result = allTidings;

    if (activeTab === "breaking") {
      // Show AI-generated (newest) first, then recent static
      result = result.filter((t) => t.id.startsWith("ai-") || t.category === "geopolitical");
    } else if (activeTab === "omens") {
      // Only high probability or Omen rarity
      result = result.filter((t) => t.probability >= 65 || (t as AiTiding).rarity === "Omen" || (t as AiTiding).rarity === "Epic");
    }

    // Apply personalized preferences for "For You"
    if (activeTab === "foryou" && preferences) {
      const { preferred_categories, preferred_traditions } = preferences;
      const hasCategories = preferred_categories.length > 0 && !preferred_categories.includes("all");
      const hasTraditions = preferred_traditions.length > 0 && !preferred_traditions.includes("all");

      if (hasCategories || hasTraditions) {
        const personalized = result.filter((t) => {
          const categoryMatch = !hasCategories || preferred_categories.includes(t.category);
          const traditionMatch = !hasTraditions || t.sources.some((s) =>
            preferred_traditions.some((pref) =>
              s.tradition.toLowerCase().includes(pref.toLowerCase())
            )
          );
          return categoryMatch || traditionMatch;
        });
        // Fallback to all if personalized filter is too strict
        if (personalized.length > 0) result = personalized;
      }
    }

    return result;
  }, [allTidings, activeTab, preferences]);

  const generateTiding = async () => {
    setIsGenerating(true);

    // Dramatic haptic pattern
    if (navigator.vibrate) navigator.vibrate([50, 30, 50, 30, 100]);

    try {
      const { data, error } = await supabase.functions.invoke("generate-tiding", {
        body: {},
      });
      if (error) throw error;
      if (data?.tiding) {

        // Rarity assignment based on probability
        let assignedRarity = data.tiding.rarity || "Common";
        if (data.tiding.probability >= 90) assignedRarity = "Omen";
        else if (data.tiding.probability >= 70) assignedRarity = "Epic";
        else if (data.tiding.probability >= 40) assignedRarity = "Rare";

        const tiding: AiTiding & { videoUrl?: string } = {
          ...data.tiding,
          rarity: assignedRarity,
          image: data.tiding.image || tidingDefault,
          videoUrl: data.tiding.videoUrl,
          newsSource: data.tiding.newsSource,
          newsUrl: data.tiding.newsUrl,
        };
        setAiTidings((prev) => [tiding, ...prev]);
        recordGenerate();

        // Rarity-based haptic intensity
        if (assignedRarity === "Omen" && navigator.vibrate) {
          navigator.vibrate([500, 100, 500, 100, 500]);
        } else if (assignedRarity === "Epic" && navigator.vibrate) {
          navigator.vibrate([200, 50, 200]);
        } else if (navigator.vibrate) {
          navigator.vibrate(100);
        }

        // Rarity-themed notification with headline count
        const rarityEmoji = { Common: "", Rare: "💎", Epic: "⚡", Omen: "🔥" }[assignedRarity] || "";
        const scannedCount = data.headlinesScanned || 0;
        const sourceNote = scannedCount > 0 ? ` · ${scannedCount} headlines scanned` : "";
        toast.success(`${rarityEmoji} ${assignedRarity} Tiding decoded${sourceNote}`);

        // Scroll to new tiding
        setCurrentIndex(0);
        setTimeout(() => scrollToIndex(0), 100);
      }
    } catch (err: any) {
      console.error("Generation error:", err);
      toast.error(err.message || "The Oracle is silent. Try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  // Auto-generate first tiding on first visit
  useEffect(() => {
    if (!hasAutoGenerated && aiTidings.length === 0) {
      setHasAutoGenerated(true);
      // Small delay for dramatic effect
      const timer = setTimeout(() => {
        generateTiding();
      }, 1500);
      return () => clearTimeout(timer);
    }
  }, [hasAutoGenerated]);

  // Track views when swiping
  const handleScroll = useCallback(() => {
    if (!scrollContainerRef.current) return;
    const container = scrollContainerRef.current;
    const scrollTop = container.scrollTop;
    const cardHeight = container.clientHeight;
    const newIndex = Math.round(scrollTop / cardHeight);
    if (newIndex !== currentIndex && newIndex >= 0 && newIndex < filtered.length) {
      setCurrentIndex(newIndex);
      setShowSwipeHint(false);
      recordView();
    }
  }, [currentIndex, filtered.length, recordView]);

  const scrollToIndex = (index: number) => {
    if (!scrollContainerRef.current) return;
    const cardHeight = scrollContainerRef.current.clientHeight;
    scrollContainerRef.current.scrollTo({ top: index * cardHeight, behavior: "smooth" });
  };

  // Reset scroll when tab changes
  useEffect(() => {
    setCurrentIndex(0);
    scrollToIndex(0);
  }, [activeTab]);

  useEffect(() => {
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = "";
    };
  }, []);

  // XP progress percentage
  const xpProgress = streak.xpToNext > 0 ? (streak.xp / streak.xpToNext) * 100 : 0;

  return (
    <div className="fixed inset-0 bg-black z-50">

      {/* ═══════════ Oracle Consulting Overlay ═══════════ */}
      {isGenerating && (
        <div className="absolute inset-0 z-[100] animate-oracle-reveal flex flex-col items-center justify-center">
          <div className="absolute inset-0 bg-black/95" />

          {/* Orbiting ring */}
          <div className="absolute w-48 h-48 border border-oracle/30 rounded-full animate-orbit" />
          <div className="absolute w-64 h-64 border border-oracle/15 rounded-full animate-orbit" style={{ animationDirection: "reverse", animationDuration: "5s" }} />

          <div className="relative z-10 flex flex-col items-center animate-omen-shake">
            <div className="relative">
              <Sparkles className="w-16 h-16 text-oracle drop-shadow-[0_0_30px_rgba(255,215,0,1)]" />
              <div className="absolute inset-0 w-16 h-16 bg-oracle/20 rounded-full blur-xl animate-pulse" />
            </div>
            <h2 className="font-display text-3xl text-white font-bold tracking-[0.2em] text-center mt-8 animate-pulse">
              CONSULTING<br />THE ORACLE
            </h2>
            <div className="mt-6 flex items-center gap-2">
              <Loader2 className="w-4 h-4 text-oracle animate-spin" />
              <span className="text-oracle/80 font-body text-xs tracking-[0.3em] uppercase">
                Decoding prophecy...
              </span>
            </div>

            {/* Fake progress stages */}
            <div className="mt-8 space-y-2 text-[10px] text-white/30 font-body">
              <p className="animate-pulse">Scanning live news feeds...</p>
              <p className="animate-pulse" style={{ animationDelay: "0.8s" }}>Filtering for prophetic signals...</p>
              <p className="animate-pulse" style={{ animationDelay: "1.6s" }}>Cross-referencing ancient texts...</p>
              <p className="animate-pulse" style={{ animationDelay: "2.4s" }}>Decoding prophecy connection...</p>
            </div>
          </div>
        </div>
      )}

      {/* ═══════════ Header Bar ═══════════ */}
      <div className="absolute top-0 left-0 right-0 z-30 bg-gradient-to-b from-black/90 via-black/60 to-transparent">
        {/* Top row: Logo + Streak + User */}
        <div className="flex items-center justify-between px-4 pt-3 pb-1">
          <div className="flex items-center gap-2">
            <h1 className="font-display text-xl font-bold text-white tracking-wider drop-shadow-[0_0_10px_rgba(255,215,0,0.6)]">
              TIDINGS
            </h1>
          </div>

          <div className="flex items-center gap-3">
            {/* Streak counter */}
            {streak.current > 0 && (
              <div className="flex items-center gap-1.5 bg-white/10 backdrop-blur-sm px-2.5 py-1 rounded-full">
                <Flame className="w-3.5 h-3.5 text-orange-400 animate-fire" />
                <span className="text-[11px] text-white font-bold font-body">{streak.current}</span>
              </div>
            )}

            {/* Seer level badge */}
            <div className="flex items-center gap-1.5 bg-oracle/20 backdrop-blur-sm px-2.5 py-1 rounded-full border border-oracle/30">
              <span className="text-[10px] text-oracle font-bold font-body tracking-wider uppercase">{streak.seerTitle}</span>
            </div>

            <UserMenu />
          </div>
        </div>

        {/* XP Bar (thin) */}
        <div className="mx-4 h-[2px] bg-white/10 rounded-full overflow-hidden mb-1">
          <div
            className="h-full bg-gradient-to-r from-oracle to-primary rounded-full transition-all duration-1000"
            style={{ width: `${xpProgress}%` }}
          />
        </div>

        {/* Tab row (TikTok-style) */}
        <div className="flex items-center justify-center gap-6 py-2">
          {TABS.map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className="relative flex flex-col items-center gap-0.5"
              >
                <div className="flex items-center gap-1.5">
                  <Icon className={`w-3.5 h-3.5 transition-colors ${isActive ? "text-white" : "text-white/40"}`} />
                  <span className={`text-[13px] font-semibold font-body transition-colors ${
                    isActive ? "text-white" : "text-white/40"
                  }`}>
                    {tab.label}
                  </span>
                </div>
                {/* Active indicator */}
                {isActive && (
                  <div className="absolute -bottom-1.5 w-8 h-[2px] bg-white rounded-full animate-tab-slide" />
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* ═══════════ Snap Scroll Feed ═══════════ */}
      <div
        ref={scrollContainerRef}
        onScroll={handleScroll}
        className="h-full w-full overflow-y-scroll snap-y snap-mandatory scrollbar-hide"
        style={{ scrollSnapType: "y mandatory" }}
      >
        {filtered.map((tiding, i) => (
          <div key={tiding.id} className="h-full w-full snap-start snap-always">
            <FullscreenTidingCard
              tiding={tiding as AiTiding}
              index={i}
              total={filtered.length}
              isActive={i === currentIndex}
              onNavigateUp={() => scrollToIndex(i - 1)}
              onNavigateDown={() => scrollToIndex(i + 1)}
              onWitness={recordReaction}
            />
          </div>
        ))}
        {filtered.length === 0 && !isGenerating && (
          <div className="h-full w-full flex flex-col items-center justify-center gap-4">
            <Sparkles className="w-12 h-12 text-oracle/50" />
            <p className="text-white/50 font-body text-sm">No tidings match this filter</p>
            <button
              onClick={() => setActiveTab("foryou")}
              className="text-oracle text-xs font-body hover:underline"
            >
              View all tidings →
            </button>
          </div>
        )}
      </div>

      {/* ═══════════ Bottom Bar ═══════════ */}
      <div className="absolute bottom-0 left-0 right-0 z-30 bg-gradient-to-t from-black/80 to-transparent pb-4 pt-8">
        {/* Swipe-up hint for first-time users */}
        {showSwipeHint && filtered.length > 1 && !isGenerating && (
          <div className="flex flex-col items-center gap-1 mb-3 animate-bounce">
            <div className="w-5 h-8 rounded-full border-2 border-white/30 flex items-start justify-center pt-1.5">
              <div className="w-1 h-2 bg-white/50 rounded-full animate-scroll-dot" />
            </div>
            <span className="text-[10px] text-white/40 font-body">Swipe up to explore</span>
          </div>
        )}
        <div className="flex items-end justify-between px-4">
          {/* Progress indicator */}
          <div className="flex items-center gap-2">
            <div className="flex gap-1">
              {filtered.slice(0, Math.min(filtered.length, 8)).map((_, i) => (
                <div
                  key={i}
                  className={`h-1 rounded-full transition-all duration-300 ${
                    i === currentIndex
                      ? "w-6 bg-white"
                      : i < currentIndex
                      ? "w-1.5 bg-white/40"
                      : "w-1.5 bg-white/15"
                  }`}
                />
              ))}
              {filtered.length > 8 && (
                <span className="text-[9px] text-white/30 font-body ml-1">+{filtered.length - 8}</span>
              )}
            </div>
          </div>

          {/* Oracle FAB */}
          <button
            onClick={generateTiding}
            disabled={isGenerating}
            className="relative flex items-center justify-center rounded-full bg-oracle shadow-[0_0_20px_rgba(255,215,0,0.4)] text-black hover:shadow-[0_0_30px_rgba(255,215,0,0.6)] transition-all hover:scale-105 active:scale-95 disabled:opacity-60"
            style={{ width: "56px", height: "56px" }}
          >
            {/* Orbiting ring decoration */}
            <div className="absolute inset-[-4px] border border-oracle/30 rounded-full animate-orbit" />
            {isGenerating ? (
              <Loader2 className="w-6 h-6 animate-spin" />
            ) : (
              <Sparkles className="w-6 h-6" />
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default Index;
