import { useState, useRef, useEffect, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { useIsMobile } from "@/hooks/use-mobile";
import TidingsHeader from "@/components/TidingsHeader";
import TidingCard from "@/components/TidingCard";
import FullscreenTidingCard from "@/components/FullscreenTidingCard";
import CategoryFilter from "@/components/CategoryFilter";
import { TIDINGS_DATA, type TidingDetail } from "@/data/tidings";
import { supabase } from "@/integrations/supabase/client";
import { Sparkles, Loader2, ArrowLeft } from "lucide-react";
import { toast } from "sonner";
import type { TidingData } from "@/components/TidingCard";
import tidingDefault from "@/assets/tiding-default.jpg";

type AiTiding = TidingData & { voiceover?: string; headline?: string; imagePrompt?: string };

const Index = () => {
  const [filter, setFilter] = useState("all");
  const [aiTidings, setAiTidings] = useState<AiTiding[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [viewMode, setViewMode] = useState<"feed" | "fullscreen">("feed");
  const [currentIndex, setCurrentIndex] = useState(0);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();
  const isMobile = useIsMobile();

  const allTidings: (TidingDetail | AiTiding)[] = [
    ...aiTidings,
    ...TIDINGS_DATA,
  ];
  const filtered = filter === "all" ? allTidings : allTidings.filter((t) => t.category === filter);

  const generateTiding = async () => {
    setIsGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-tiding", {
        body: {},
      });
      if (error) throw error;
      if (data?.tiding) {
        // Use default oracle image for AI tidings
        const tiding: AiTiding = {
          ...data.tiding,
          image: tidingDefault,
        };
        setAiTidings((prev) => [tiding, ...prev]);
        toast.success("New tiding generated by the Oracle");
        // Switch to fullscreen to show it
        if (isMobile) {
          setViewMode("fullscreen");
          setCurrentIndex(0);
        }
      }
    } catch (err: any) {
      console.error("Generation error:", err);
      toast.error(err.message || "Failed to generate tiding");
    } finally {
      setIsGenerating(false);
    }
  };

  // Handle scroll snap for fullscreen mode
  const handleScroll = useCallback(() => {
    if (!scrollContainerRef.current) return;
    const container = scrollContainerRef.current;
    const scrollTop = container.scrollTop;
    const cardHeight = container.clientHeight;
    const newIndex = Math.round(scrollTop / cardHeight);
    if (newIndex !== currentIndex && newIndex >= 0 && newIndex < filtered.length) {
      setCurrentIndex(newIndex);
    }
  }, [currentIndex, filtered.length]);

  const scrollToIndex = (index: number) => {
    if (!scrollContainerRef.current) return;
    const cardHeight = scrollContainerRef.current.clientHeight;
    scrollContainerRef.current.scrollTo({ top: index * cardHeight, behavior: "smooth" });
  };

  useEffect(() => {
    if (viewMode === "fullscreen") {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [viewMode]);

  // Desktop/tablet feed view
  if (!isMobile || viewMode === "feed") {
    return (
      <div className="min-h-screen bg-background">
        <div className="max-w-2xl mx-auto px-4 pb-16">
          <TidingsHeader />

          {/* AI Generate button */}
          <div className="mb-4">
            <button
              onClick={generateTiding}
              disabled={isGenerating}
              className="w-full flex items-center justify-center gap-2 bg-gradient-oracle text-oracle-foreground py-3 rounded-lg text-sm font-semibold shadow-oracle hover:opacity-90 transition-opacity disabled:opacity-50 font-body"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Consulting the Oracle...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  Generate AI Tiding
                </>
              )}
            </button>
          </div>

          <div className="mb-6 flex items-center justify-between gap-4">
            <div className="flex-1">
              <CategoryFilter onFilterChange={setFilter} />
            </div>
            {isMobile && (
              <button
                onClick={() => setViewMode("fullscreen")}
                className="px-3 py-2 bg-secondary text-secondary-foreground text-xs rounded-lg font-body"
              >
                Fullscreen
              </button>
            )}
          </div>

          <div className="space-y-6">
            {filtered.map((tiding) => (
              <div
                key={tiding.id}
                onClick={() => {
                  if (tiding.id.startsWith("ai-")) {
                    toast.info("AI tidings don't have detail pages yet");
                  } else {
                    navigate(`/tiding/${tiding.id}`);
                  }
                }}
                className="cursor-pointer"
              >
                <TidingCard tiding={tiding} />
              </div>
            ))}
          </div>
          {filtered.length === 0 && (
            <div className="text-center py-20 text-muted-foreground font-body">
              No tidings found for this category.
            </div>
          )}
        </div>
      </div>
    );
  }

  // Mobile fullscreen TikTok-style view
  return (
    <div className="fixed inset-0 bg-background z-50">
      {/* Header overlay */}
      <div className="absolute top-0 left-0 right-0 z-30 flex items-center justify-between p-4 bg-gradient-to-b from-background/80 to-transparent">
        <button
          onClick={() => setViewMode("feed")}
          className="p-2 rounded-full bg-secondary/60 backdrop-blur-sm text-secondary-foreground"
        >
          <ArrowLeft className="w-5 h-5" />
        </button>
        <h1 className="font-display text-lg font-bold text-gradient-gold">TIDINGS</h1>
        <button
          onClick={generateTiding}
          disabled={isGenerating}
          className="p-2 rounded-full bg-oracle/80 backdrop-blur-sm text-oracle-foreground"
        >
          {isGenerating ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
        </button>
      </div>

      {/* Filter pills */}
      <div className="absolute top-16 left-0 right-0 z-30 px-4">
        <CategoryFilter onFilterChange={setFilter} />
      </div>

      {/* Snap scroll container */}
      <div
        ref={scrollContainerRef}
        onScroll={handleScroll}
        className="h-full w-full overflow-y-scroll snap-y snap-mandatory"
        style={{ scrollSnapType: "y mandatory" }}
      >
        {filtered.map((tiding, i) => (
          <div key={tiding.id} className="h-full w-full snap-start snap-always">
            <FullscreenTidingCard
              tiding={tiding as AiTiding}
              index={i}
              total={filtered.length}
              onNavigateUp={() => scrollToIndex(i - 1)}
              onNavigateDown={() => scrollToIndex(i + 1)}
            />
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="h-full w-full flex items-center justify-center">
            <p className="text-muted-foreground font-body">No tidings found.</p>
          </div>
        )}
      </div>

      {/* Page indicator */}
      <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-30">
        <div className="bg-secondary/60 backdrop-blur-sm px-3 py-1 rounded-full text-xs text-secondary-foreground font-body">
          {currentIndex + 1} / {filtered.length}
        </div>
      </div>
    </div>
  );
};

export default Index;
